#!/usr/bin/env node
/**
 * MDC-ALL — the MDC's own ladder, and the `mdc-ladder` entry in the campaign's standing
 * regression manifest (contract §4, X1).
 *
 * IT MAY NOT PRINT `MDC-ALL OK` OVER AN EMPTY LADDER. P4 and P5 both recorded this in as many
 * words, and it is the whole reason this file exists before any gate does: with no gates written,
 * the honest verdict is `MDC-ALL INCOMPLETE`, naming every required gate as MISSING. A runner that
 * reports success because it found nothing to run is the defect the campaign exists to prevent.
 *
 * Three verdicts, and they are distinguishable on purpose:
 *
 *   MDC-ALL OK           every required gate ran and passed
 *   MDC-ALL INCOMPLETE   nothing failed, but something did not run — missing, not implemented,
 *                        or not evaluable in this environment
 *   MDC-ALL FAILED       something ran and failed
 *
 * The required set comes from tools/mdc/required-gates.json, which is GENERATED from the contract
 * fence by campaign-master/bin/mdc-required-gates.mjs. This runner refuses a required set it
 * cannot read: a ladder that falls back to "whatever gates are on disk" can only ever confirm the
 * work somebody remembered to do.
 */
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { gateNames, runGate, activeRequiredGates } from './gate.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');

const git = (...args) => {
  try { return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim(); }
  catch { return ''; }
};

const sha = git('rev-parse', 'HEAD').slice(0, 12) || 'unknown';
const dirty = git('status', '--porcelain').length > 0;

const main = async () => {
  process.stdout.write('\nMDC-ALL — the MDC ladder\n');
  process.stdout.write(`  sha ${sha}${dirty ? ' (WORKTREE DIRTY)' : ''}  node ${process.version}\n\n`);

  const r = activeRequiredGates();
  if (r.error) {
    process.stdout.write(`  ${r.error}\n\nMDC-ALL FAILED — the required set is unreadable\n\n`);
    process.exit(1);
  }

  const onDisk = new Set(gateNames());
  const results = [];
  const missing = [];

  for (const req of r.active) {
    if (!onDisk.has(req.gate)) {
      missing.push(req);
      process.stdout.write(`  MISSING  ${req.gate.padEnd(22)} ${req.criteria.join(',').padEnd(5)} required by the contract, no module on disk\n`);
      continue;
    }
    const started = Date.now();
    const res = await runGate(req.gate);
    const ms = Date.now() - started;
    results.push({ ...res, criteria: req.criteria, stage: req.stage, ms });
    const status = res.ok ? 'ok     ' : res.notImplemented ? 'NOT-IMP' : res.notEvaluated ? 'NOT-EVL' : 'FAIL   ';
    process.stdout.write(`  ${status}  ${req.gate.padEnd(22)} ${String(ms + 'ms').padStart(7)}  ${res.ok ? res.sentinel : res.message.split('\n')[0].slice(0, 96)}\n`);
  }

  // A gate on disk that the contract does not require is reported, never silently counted.
  const extra = [...onDisk].filter((g) => !r.required.gates.some((x) => x.gate === g));

  const failed = results.filter((x) => !x.ok && !x.notImplemented && !x.notEvaluated);
  const notImpl = results.filter((x) => x.notImplemented);
  const notEval = results.filter((x) => x.notEvaluated);
  const passed = results.filter((x) => x.ok);

  process.stdout.write('\n');
  process.stdout.write(`  required now ${r.active.length} · ran ${results.length} · passed ${passed.length} · failed ${failed.length}`);
  process.stdout.write(` · missing ${missing.length} · not implemented ${notImpl.length} · not evaluated ${notEval.length}\n`);
  process.stdout.write(`  not yet in scope: ${r.later.length} gate(s) — ${r.later.map((g) => g.stage).filter((v, i, a) => a.indexOf(v) === i).join(' ')}\n`);
  if (extra.length) process.stdout.write(`  gates present but NOT required by the contract: ${extra.join(', ')}\n`);

  const report = {
    $comment: 'Generated by tools/mdc/all.mjs. The verdict is the printed sentinel, not this file.',
    sha: git('rev-parse', 'HEAD'),
    worktreeDirty: dirty,
    node: process.version,
    contractFenceHash: r.required.contractFenceHash,
    activeStages: r.required.activeStages,
    requiredNow: r.active.length,
    missing: missing.map((m) => ({ gate: m.gate, criteria: m.criteria })),
    results: results.map(({ detail, ...x }) => x),
  };
  const dir = join(ROOT, 'reports', 'mdc');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const reportPath = join(dir, `${sha}${dirty ? '-dirty' : ''}.json`);
  writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  process.stdout.write(`  report  reports/mdc/${sha}${dirty ? '-dirty' : ''}.json\n\n`);

  if (failed.length) {
    process.stdout.write(`MDC-ALL FAILED — ${failed.length} gate(s): ${failed.map((f) => f.name).join(', ')}\n\n`);
    process.exit(1);
  }
  if (missing.length || notImpl.length || notEval.length) {
    const parts = [];
    if (missing.length) parts.push(`${missing.length} missing (${missing.map((m) => m.gate).join(', ')})`);
    if (notImpl.length) parts.push(`${notImpl.length} not implemented`);
    if (notEval.length) parts.push(`${notEval.length} not evaluated`);
    process.stdout.write(`MDC-ALL INCOMPLETE — nothing failed, but ${parts.join(' · ')}. A ladder may not report OK over work it did not run.\n\n`);
    process.exit(1);
  }
  if (!r.active.length) {
    process.stdout.write('MDC-ALL INCOMPLETE — no gate is required at the current stage, so this ladder measured nothing. A check over zero gates is not a passing check.\n\n');
    process.exit(1);
  }
  process.stdout.write(`MDC-ALL OK — every required gate green (${passed.length} of ${r.active.length})\n\n`);
};

await main();
